# Un/Users/viren8694/Desktop/RJT_Program/Assignments/FirebaseUsers/Podfilecomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseUsers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'SVProgressHUD'
pod 'TWMessageBarManager'
pod 'AlamofireImage', '~> 3.3'
pod 'Firebase/Storage'
pod 'GooglePlaces'
pod 'SDWebImage','~> 4.0'
pod 'GoogleSignIn'

  # Pods for FirebaseUsers

  target 'FirebaseUsersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseUsersUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
